### ISSUE TITLE
BOM not available via official maven repos

### ISSUE THREAD

**Issue by davidbilge** [FasterXML/jackson-bom#1]
I would like to use this bom in my project to make sure that all jackson libs that are being pulled in via various transitive dependencies match up.

To accomplish that, you would normally do 

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>${jackson.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

which does not work for me, because maven can not find this artifact anywhere in the official repos. Are there any plans to publish this?

**Comment by davidbilge** [comment]
btw: There is an inofficial jackson-bom-project on github (https://github.com/joschi/jackson-bom) which is available via the maven repos. Maybe the author should be made aware of the official alternative here as soon as it is usable?

**Comment by christophercurrie** [comment]
This should be out in a day or so. We're aware of the unofficial repo and the maintainer knows that we're publishing an official one.

**Comment by christophercurrie** [comment]
I have release version 2.8.3; I would appreciate it if you would kick the tires on that release before I move ahead with 2.8.4.

**Comment by davidbilge** [comment]
Can not find it yet, local maven won't and it is not listed on mvnrepository.com or search.maven.org. I guess we have to give it some time to propagate :)

I'll try again later.

**Comment by davidbilge** [comment]
Alright, it works now. Maven is able to resolve the dependency and it appears on search.maven.org. mvnrepository.com does not list it yet but that will only be a matter of time.

From my perspective, this is fixed.
