### ISSUE TITLE
Latest 2.8.11 bom does not include the latest micro-patch version of jackson-databind, 2.8.11.1

### ISSUE THREAD

**Issue by wilkinsona** [FasterXML/jackson-bom#11]
Would it be possible to release a 2.8.11.1 version of the bom that pulls in jackson-databind:2.8.11.1?

**Comment by cowtowncoder** [comment]
Unfortunately not really, in that there is (and won't be) full set of micro-patches, as they are released on one-by-one basis. I guess if Maven/Gradle allowed other patch identifiers (do they?), there would be ... well. Perhaps something like

     2.8.11.20180216

which would simply indicate "latest patch/micro-patch at this date"?

So the reason `2.8.11.1` would not work is that this patch may become available of any components, at a later point. So using it for pom would be misleading.

But maybe timestamped version would be acceptable? That would seem reasonable (if not optimal) to me.

**Comment by Stephan202** [comment]
The argument for not going with `2.8.11.1` makes sense. Timestamps would work for our team.

**Comment by cowtowncoder** [comment]
Just pushed `jackson-bom` version `2.8.11.20180217`, should get to Maven Central shortly.
