### ISSUE TITLE
jackson-modules-java8 not represented in bom

### ISSUE THREAD

**Issue by rhanton** [FasterXML/jackson-bom#16]
The modules mentioned at https://github.com/FasterXML/jackson-modules-java8 are listed as deprecated in the locations listed in this bom, with the request to retrieve them from com.fasterxml.jackson.module after jackson 2.8.5. This change should be represented in the bom versions > 2.8.5 as well.

**Comment by cowtowncoder** [comment]
Missed this originally so I do not have context, but I think modules included should be correct since 2.10 at least.

**Comment by ncorai** [comment]
The jackson-modules-java8 section remains missing in the BOM

**Comment by cowtowncoder** [comment]
@ncorai Which version of BOM? Which specific modules?

**Comment by ncorai** [comment]
Artifact `jackson-modules-java8` is missing from https://github.com/FasterXML/jackson-bom/blob/2.13/pom.xml
whereas the following obsolete artifacts it replaces are still listed:
`jackson-module-parameter-names`
`jackson-datatype-jsr310`
`jackson-datatype-jdk8`

**Comment by ncorai** [comment]
On page https://github.com/FasterXML/jackson-module-parameter-names it states:
"NOTE: This module has become part of Jackson Java 8 Modules as of Jackson 2.8.5
This repo still exists to allow release of patch versions of older versions; it will be hidden (made private) in near future."

**Comment by cowtowncoder** [comment]
Ah. Right, `jackson-modules-java8` is the Github repo, not Jackson module. The parent level specifies pom-only artifact which no one should depend on or import; it does NOT act as a short cut for including 3 actual modules.

**Comment by ncorai** [comment]
Ah OK. Even after reading about parent pom.xml files, I still don't grasp the purpose of publishing them (but then I've only used maven for artifact coordinates). I'll figure that out another time, I guess. Thanks for the clarification.
