### ISSUE TITLE
Issues downloading files for Maven3.6.0

### ISSUE THREAD

**Issue by ambuj369** [FasterXML/jackson-bom#18]
[WARNING] Could not validate integrity of download from http://repo.odysseusinc.com/artifactory/community-libs-release-local/com/fasterxml/jackson/jackson-bom/2.8.7/jackson-bom-2.8.7.pom: Checksum validation failed, expected <!DOCTYPE but is eaf36286872dacdc1ed59d9a43ca8eb7b1b40103

[WARNING] Checksum validation failed, expected <!DOCTYPE but is eaf36286872dacdc1ed59d9a43ca8eb7b1b40103 from odysseus.community.releases for http://repo.odysseusinc.com/artifactory/community-libs-release-local/com/fasterxml/jackson/jackson-bom/2.8.7/jackson-bom-2.8.7.pom

[WARNING] Could not validate integrity of download from http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/apache/logging/log4j/log4j-bom/2.7/log4j-bom-2.7.pom: Checksum validation failed, expected <!DOCTYPE but is a0858d0def28f2cfdbe71c81ed738cad014a07f1

[WARNING] Checksum validation failed, expected <!DOCTYPE but is a0858d0def28f2cfdbe71c81ed738cad014a07f1 from odysseus.community.releases for http://repo.odysseusinc.com/artifactory/community-libs-release-local/org/apache/logging/log4j/log4j-bom/2.7/log4j-bom-2.7.pom

These error and the file getting downloaded are throwing random errors when being called to build a .war file in CentOS.

Maven verison : 3.6.0
Java 8
O.S. CentOS7

please suggest where can I get it downloaded in correct format without any issues.
Below is the snippet from my POM.XML which is calling the urls to download.
      <url>http://repo.odysseusinc.com/artifactory/community-libs-snapshot-local</url>
    </repository>
    <repository>
      <id>odysseus.community.releases</id>
      <name>Odysseus community releases</name>
      <releases>
        <enabled>true</enabled>
        <updatePolicy>always</updatePolicy>
      </releases>
      <snapshots>
        <enabled>false</enabled>
        <updatePolicy>always</updatePolicy>
      </snapshots>
      <url>http://repo.odysseusinc.com/artifactory/community-libs-release-local</url>
    </repository>
   Attached are the screenshot for the errors I am receiving.
   
    Thanks In Advance

**Comment by Stephan202** [comment]
Hi @ambuj369. This looks like an issue within the Odysseus Artifactory instance. Fetching the first artifact you mentioned from [Maven Central](https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.8.7/jackson-bom-2.8.7.pom) works just fine.

**Comment by ambuj369** [comment]
Hi @Stephan202 , so shall I update my POM.xml file with new repository location and try ?

**Comment by Stephan202** [comment]
@ambuj369 Maven Central is the default, so simply dropping the custom repository configuration from your `pom.xml` may help. But the original author probably placed it there for a reason. So if you are in any way related to Odysseus, I'd reach out to them.

**Comment by ambuj369** [comment]
@Stephan202 Could it be due to internet firewall? Because when I open the associated repository links, those sites doesn't appear and screen shows the firewall message.
let me know your thoughts on this.
Thank you.

**Comment by Stephan202** [comment]
@ambuj369 that's definitely possible. Can't help debug beyond that though, since the issue appears to be very specific to your setup.

**Comment by ambuj369** [comment]
@Stephan202 , hope you has a great weekend.
So, I remove firewall restrictions from network and still I am getting the same Warning messages. In addition, I tried to open the link 
http://repo.odysseusinc.com/artifactory/community-libs-release-local/com/fasterxml/jackson/jackson-bom/2.8.7/jackson-bom-2.8.7.pom
 and it says 

errors |  
-- | --
0 |  
status | 404
message | "File not found."

Please help and if you can reach out to Odysseus regarding this, that would be very helpful.

TIA

**Comment by Stephan202** [comment]
I don't know Odysseus and certainly won't reach out to them. But a closer inspection indicates that the repo you're pointing to only hosts "local" artifacts (presumably those built by Odysseus). Their [Artifactory deployment](http://repo.odysseusinc.com/artifactory) does expose Jackson as part of other repos:
* http://repo.odysseusinc.com/artifactory/remote-repos/com/fasterxml/jackson/jackson-bom/2.8.7/jackson-bom-2.8.7.pom -> this looks like a "proxy repo"
* http://repo.odysseusinc.com/artifactory/libs-release/com/fasterxml/jackson/jackson-bom/2.8.7/jackson-bom-2.8.7.pom -> this looks like a "unified (hosted + proxy) repo"

So if in your `pom.xml` you change the URL by replacing `community-libs-snapshot-local` with `libs-release`, it may work.

If not, I don't think I can help you any further, sorry.

**Comment by ambuj369** [comment]
@Stephan202 The change in the url for snapshot actually worked for a span of time and that might help. Similarly, can you please let me know what change should I do to the following url.
http://repo.odysseusinc.com/artifactory/community-libs-release-local/com/fasterxml/jackson/jackson-bom/2.8.7/jackson-bom-2.8.7.pom
