### ISSUE TITLE
jackson-annotations not updated in the 2.9.x BOM

### ISSUE THREAD

**Issue by gsmet** [FasterXML/jackson-bom#23]
Hi,

In https://github.com/FasterXML/jackson-bom/blob/2.9/pom.xml#L39 , you can see that jackson-annotations is still at `2.9.0` whereas there are quite a lot of new versions released: latest 2.9 is `2.9.9`.

It wouldn't be an issue if there weren't any changes but `2.9.1` brings an automatic module name so it would be nice to upgrade.

Thanks!

**Comment by cowtowncoder** [comment]
This was changed so that the latest 2.9 versions (and in particular, 2.9.10 and micro-patches) used later annotations version.
