### ISSUE TITLE
BOM 2.9.9.20190806 refers to previous jackson-databind release

### ISSUE THREAD

**Issue by snicoll** [FasterXML/jackson-bom#24]
Per https://github.com/FasterXML/jackson-databind/issues/2395#issuecomment-518465813, I thought that `2.9.9.20190806` would upgrade `jackson-databind` to `2.9.9.3` but this bom [still refers to `2.9.9.2`](https://search.maven.org/artifact/com.fasterxml.jackson/jackson-bom/2.9.9.20190806/pom)

**Comment by snicoll** [comment]
@cowtowncoder I think this can be closed now.

**Comment by cowtowncoder** [comment]
Resolved by a new bom, `2.9.9.20190807`.
