### ISSUE TITLE
jackson-datatype-eclipse-collections not Represented in BOM

### ISSUE THREAD

**Issue by rinatigati** [FasterXML/jackson-bom#25]
For some reason the Eclipse Collections jackson module is not represented in this BOM. Every other collection from [jackson-datatype-collections](https://github.com/FasterXML/jackson-datatypes-collections) is represented in the BOM, but not the Eclipse Collections module.

This has to be an oversight, right?

**Comment by AceHack** [comment]
I have this same issue, will this be fixed?

**Comment by cowtowncoder** [comment]
Yes, that is an oversight: unfortunately I did not see this issue until now. Will add, to be included for 2.10.5, 2.11.3 and 2.12.0.
