### ISSUE TITLE
JUnit 4 dependency version is also resolved when importing jackson-bom in a project

### ISSUE THREAD

**Issue by gastaldi** [FasterXML/jackson-bom#28]
Because JUnit 4 is declared in `jackson-parent` POM's dependencyManagement, this dependency version is also resolved when the jackson BOM is imported.

**Comment by gastaldi** [comment]
Seems to be fixed in https://github.com/FasterXML/jackson-bom/commit/1da8286078e447b1e093f9dd10b6c922b91afeb9, closing

**Comment by facboy** [comment]
is this never going to be fixed in 2.x?
