### ISSUE TITLE
jackson-bom-2.10.2.20200129 depends on jackson.version 2.10.3-SNAPSHOT.

### ISSUE THREAD

**Issue by kreiger** [FasterXML/jackson-bom#30]
This causes Gradle builds with a dependency of

    compile platform("com.fasterxml.jackson:jackson-bom:2.10.+")

to fail with e.g.

    Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find com.fasterxml.jackson.datatype:jackson-datatype-jdk8:2.10.3-SNAPSHOT.
    Searched in the following locations:
      - ...
      - ...

**Comment by cowtowncoder** [comment]
That is unfortunate and essentially means that version is useless, but unfortunately Maven artifacts are immutable so it is what it is. So instead one should use later 2.10.3 or 2.10.4 boms.
