### ISSUE TITLE
Feature Request: Follow Maven pre-release versioning convention

### ISSUE THREAD

**Issue by daniel-shuy** [FasterXML/jackson-bom#31]
I would like to request that pre-release versions follow the Maven convention by including one of the following qualifiers (as defined in https://maven.apache.org/pom.html#Version_Order_Specification):
- `alpha` / `A`
- `beta` / `B`
- `milestone` / `M`
- `RC`
- `CR`
- `SNAPSHOT`

eg. `jackson-bom-2.10.2-SNAPSHOT20200130` instead of `jackson-bom-2.10.2.20200130`

This will allow tools like [WhiteSource Renovate](https://renovate.whitesourcesoftware.com/) to properly ignore pre-releases.

**Comment by cowtowncoder** [comment]
For 2.11, pre-release modifier of "rcX" was used (although there is some concern that 2.11.0.rc1 causes issues for some systems -- dot is for OSGi compatibility, as apparently OSGi can not use 2.11.0-rc1 dep -- but this may be changed).

Version `jackson-bom-2.10.2.20200130`, however, is NOT a pre-release candidate at all.
It is a special micro-patch version used for consistent set in case where there is no full patch version released (usually after last full minor release for given minor version, but occasionally earlier for security patches). Use of timestamp is to indicate that is not a full set, and to maintain Maven ordering wrt newer release.

I am not sure what semantics should be used by 3rd party tools but such releases are not pre-release versions and I don't think they should be labeled as such.

So I guess this could be misunderstanding wrt versioning here. But if there is an actual problem I would like to understand it.

**Comment by daniel-shuy** [comment]
> Version jackson-bom-2.10.2.20200130, however, is NOT a pre-release candidate at all.
It is a special micro-patch version used for consistent set in case where there is no full patch version released (usually after last full minor release for given minor version, but occasionally earlier for security patches). Use of timestamp is to indicate that is not a full set, and to maintain Maven ordering wrt newer release.

I see. If that's the case then it should be safe to update to it, which is no longer an issue thanks.

**Comment by cowtowncoder** [comment]
@daniel-shuy correct.
