### ISSUE TITLE
2.8 BOM went backwards on jackson-annotations dependency

### ISSUE THREAD

**Issue by umcodemonkey** [FasterXML/jackson-bom#4]
I understand your desires around jackson-annotations versioning going forward. I don't agree with them, because I think it complicates things for end users, but I understand why you hold the position you do.

However, the 2.8.6 bom depends on version 2.8.0 of annotations, when later versions of annotations exist. If any project transitively depends on a later version of annotations, the maven-dependency-versions-check plugin will complain, because the BOM pins the version to 2.8.0, and it sees that a different project needs a later version, which would be a problem if the later version actually had different behavior, such as fixing a bug the other project depends on.

I can resolve this issue by adding another dependency management section to pin jackson-annotations to 2.8.6, but that defeats the purpose of the BOM anyway.

This problem will go away in 2.9.x, as I presume you will not release any annotations version other that 2.9.0. But for 2.8.7+, I would like to see the existing pattern continue, and keep annotations in step with other packages.

**Comment by hazendaz** [comment]
This further complicates things in environments were we are forced to use consistent version for the framework and annotations piece gets divested in our system constantly along with the entire framework.  Personally I see no reason to release annotations different than any other module, change or not.  I second that this highly deviates consistency and has long been a considered issue with annotations being released on 2.8.x and earlier each time.  Why should that change and why not just keep the components all sync'd on same version number?

**Comment by cowtowncoder** [comment]
Given that 2.8 branch is closed, except for possible micro-patches, I'll close this issue.
No more full releases are forth-coming, and likely no bom versions either
