### ISSUE TITLE
Jakarta 9 artifact versions are missing from jackson-bom

### ISSUE THREAD

**Issue by ctubbsii** [FasterXML/jackson-bom#40]
The following jakarta classifier variants (and probably others) are not present in jackson-bom, and therefore the bom cannot be used to manage dependency versions for these:

```xml
      <dependency>
        <groupId>com.fasterxml.jackson.jaxrs</groupId>
        <artifactId>jackson-jaxrs-base</artifactId>
        <version>${jackson.version}</version>
        <classifier>jakarta</classifier>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.jaxrs</groupId>
        <artifactId>jackson-jaxrs-json-provider</artifactId>
        <version>${jackson.version}</version>
        <classifier>jakarta</classifier>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.module</groupId>
        <artifactId>jackson-module-jaxb-annotations</artifactId>
        <version>${jackson.version}</version>
        <classifier>jakarta</classifier>
      </dependency>
```

These classifier variants should be included in the jackson-bom, or if that isn't possible, then a jackson-bom with the jakarta classifier should exist to contain these variants.

**Comment by cowtowncoder** [comment]
Sounds reasonable, will try to get this in for 2.12.2 (to be released soon now).
Thank you for suggestion!

**Comment by cowtowncoder** [comment]
@ctubbsii Added entries to bom; not sure if it'd be easy/possible to verify this with 2.12.2-SNAPSHOT (I did `mvn deploy` to get that to Sonatype OSS repo snapshots).

**Comment by ctubbsii** [comment]
@cowtowncoder Thanks. Your change should work fine for the jaxrs dependencies I mentioned above (as well as others). I noticed you didn't include the jakarta variants for the `.module` libraries (like `jackson-module-jaxb-annotations` mentioned above) in your commit 7d4f041c9819013ee1e80ffe52c077d63feda2e5. Was that an oversight, or intentional?

**Comment by cowtowncoder** [comment]
@ctubbsii oh. I simply missed reference you had there! (for some reason read it as "base, json and xml" for jaxrs)
I did actually start thinking about that module since I suspect it is actually missing a transformation (wrt OSGi bundle manifest), but forgot to add it.

Will add the jaxb annotations module variant too. Thanks!

**Comment by cowtowncoder** [comment]
Note: added one more jakarta variant for `jackson-datatype-jsr353` (see https://github.com/FasterXML/jackson-datatypes-misc/issues/6).
