### ISSUE TITLE
Comment in pom.xml should be "All about THAT base"

### ISSUE THREAD

**Issue by djett41** [FasterXML/jackson-bom#41]
We ran into a blocker in which we found the comment [here](https://github.com/FasterXML/jackson-bom/blob/master/pom.xml#L24) says "It's all about **the** base 'bout **the** base...", however it should read "It's all about **that** base 'bout **that** base...".

**Comment by cowtowncoder** [comment]
Uh oh. No wonder BOM functionality didn't boom like it should have! Will fix.
